create table if not exists processed_transaction (
    id bigint primary key,
    transaction_date date not null,
    amount decimal(19,2) not null,
    transaction_type varchar(20) not null
);

create table if not exists interest_result (
    account_id bigint primary key,
    holder_name varchar(120) not null,
    account_type varchar(30) not null,
    balance decimal(19,2) not null,
    monthly_interest decimal(19,2) not null
);

create table if not exists annual_statement (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    movement_date date not null,
    movement_type varchar(30) not null,
    amount decimal(19,2) not null,
    description varchar(255) not null
);
